# Generated by Django 6.0.6 on 2026-06-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_image'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='questions', to='topics.topic'),
        ),
    ]
